version: 2

references:
  cache_key: &cache_key
    jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    docker:
      - image: circleci/android:api-28
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Run Lint and Tests
          command: ./gradlew check testDebug
      - save_cache:
          key: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - store_artifacts:
          path: lifecycle-extensions/build/reports
      - store_artifacts:
          path: lifecycle-livedata/build/reports
      - store_artifacts:
          path: lifecycle-viewmodel/build/reports
      - store_artifacts:
          path: lifecycle-viewmodel-savedstate/build/reports
      - store_artifacts:
          path: room-runtime/build/reports
      - store_artifacts:
          path: room-rxjava2/build/reports
      - store_artifacts:
          path: work-runtime/build/reports
      - store_test_results:
          path: lifecycle-extensions/build/test-results
      - store_test_results:
          path: lifecycle-livedata/build/test-results
      - store_test_results:
          path: lifecycle-viewmodel/build/test-results
      - store_test_results:
          path: lifecycle-viewmodel-savedstate/build/test-results
      - store_test_results:
          path: room-runtime/build/test-results
      - store_test_results:
          path: room-rxjava2/build/test-results
      - store_test_results:
          path: work-runtime/build/test-results
